### ISSUE TITLE
OID-IP URL is wrong on systems with canonical URLs

### ISSUE THREAD

**Issue by wehowski** [danielmarschall/oidplus#14] opened 2023-05-22 16:53 UTC
https://registry.frdl.de/?goto=oidplus%3Awhois
The Link/Button "Open in Browser" does not work in IE.

Chrome: OK
FF: OK
IE: Error with Slash / Link Edit: tested with Edge

**Comment by wehowski** [comment] 2023-05-23 10:52
Yes, you can see it in a screenshot:
![Unbenannt](https://github.com/danielmarschall/oidplus/assets/2658030/4dbf8bb3-985c-474b-8cb0-69f6817459b7)

**Comment by danielmarschall** [comment] 2023-05-23 13:01
Ok, I tried it with Edge now. But I cannot reproduce it.

1. I open Edge
2. I visit registry.frdl.de
3. On the left menu I click OID-Whois
4. On the bottom of the page I click "Open in webbrowser"

For me, the URL is
https://registry.frdl.de/plugins/viathinksoft/publicPages/100_whois/whois/webwhois.php?query=oid%3A1.3.6.1.4.1

**Comment by wehowski** [comment] 2023-05-23 13:43
I can only reproduce the error at the canonical: https://webfan.de/apps/registry/index.php?goto=oidplus%3Awhois
On registry.frdl.de it is working.

**Comment by danielmarschall** [comment] 2023-05-23 13:54
Thank you. With the canonical URL I can reproduce that on Safari . It should be independent of the web browser, because IIRC the URL comes from the server side webpath() method.

**Comment by danielmarschall** [comment] 2023-05-25 12:44
If you call this URL, it works: https://webfan.de/apps/registry/?goto=oidplus%3Awhois

So, the problem is the "index.php" . It needs to be removed by JavaScript.

Also check if the PHP variant of getSystemUrl() works correctly.

**Comment by danielmarschall** [comment] 2023-05-25 12:58
Fixed method:

```
function getSystemUrl(relative) {
        relative = (typeof relative === 'undefined') ? false : relative; // do not translate
        var url = new URL(window.location.href);
        var res = relative ? url.pathname : url.href.substr(0, url.href.length-url.search.length);
        if (res.endsWith("index.php")) res = res.substring(0, res.lastIndexOf('/')) + "/";
        return res;
}

```

**Comment by wehowski** [comment] 2023-05-26 09:19
Hello Daniel,
where do I find oidplus_base.js?
Does it help to check if '/' === url.substr(0,1) ?
As the canonical end with index.php  and its a index file could remove index.php from canonical?

**Comment by danielmarschall** [comment] 2023-05-26 09:44
It is in includes/ .
Did you try my fix?

How did index.php come from in the first place?

**Comment by wehowski** [comment] 2023-05-26 10:23
1. The "/" was missing?
2.  However, yes "oidplus_base.js is in includes/ ." Your fix is working!!!

Thank you!!!

**Comment by wehowski** [comment] 2023-05-26 10:25
2. Your fix is working! 	<link rel="canonical" href="https://webfan.de/apps/registry/index.php?goto=oidplus%3Awhois"> ist contains index.php?
However, the links are working now!

**Comment by danielmarschall** [comment] 2023-05-26 11:41
Fixed this issue on serverside in `canonicalURL()`:
```
                // Third part: File name
                $tmp = $_SERVER['SCRIPT_NAME'];
                $tmp = rtrim($tmp, 'index.php'); // <-- added
                $tmp = explode('/',$tmp);
                $tmp = end($tmp);

```

**Comment by danielmarschall** [comment] 2023-05-26 11:51
Issues fixed in SVN Rev 1287

One last check (TODO): Check if there are other places where "index.php" is automatically added to the URL!

**Closed** 2023-05-26 20:12 UTC
